extend-luogu/extend-luogu

extend-luogu.user.js
!- Now use regular expressions to determine whether to execute in `mod.execute`.
! However, the `*` in the end is still regarded as matching anything.
*> Fixed the spelling of "Launching".
: "Lauching" before.
-- Added random problem in training lists.
: Users are now able to randomly choose problems in training list pages.
=> VER 1.4.0 Random Training List Update

LICENSE, extend-luogu.user.js, package.json
- 543949c00bbdca96e18af556e77cd1e81fd8dc4e SUM [LICENSE] Add Apache-2.0 License
```
!? Apache-2.0 License
: Licensed under Apache License, Version 2.0
& https://www.apache.org/licenses/LICENSE-2.0
& https://choosealicense.com/licenses/apache-2.0/
& https://spdx.org/licenses/Apache-2.0.html
& https://opensource.org/licenses/Apache-2.0
& https://www.gnu.org/licenses/license-list.html#apache2
```
=> [LICENSE] Apache License, Version 2.0

extend-luogu.user.js
-M Added options about problem samples.
: Now users can choose whether the program offers unaccepted or new problems.
: Specified notifications when accepted all samples problems with different options.
^M Fixed the bug that random problem button will not appear in certain pages.
=> VER 2.4.0 Random TrainingList Update II

extend-luogu.user.js
*M sponsor-tag
*- replaced style
*< removed extra semicolon
=> VER 2.5.3 Sponsor Tag

extend-luogu.user.js
*M dash bridge.
: added css like exlg-color or unselectable.
$M rand problem ex.
: removed f*cking i and j
=> VER 2.5.4 Minor repairs

extend-luogu.user.js
*M replaced some styles
-- added some styles
*- replaced some styles
x- removed some styles
=> VER 2.5.8 Replaced Some Styles

extend-luogu.user.js
=> VER 2.5.9 Fix Bug

extend-luogu.user.js
*M sponsor-tag
*- replaced `1rem` by `1em`
=> VER 2.5.16 Sponsor Tag

README-CN.md, README.md
```
- 添加中文readme
x 删除明显过期内容
```
=> VER 2.5.16 Update Chinese Readme

extend-luogu.user.js
-M Added Module tasklist-ex, provides a better tasklist.
-- Added auto-deletion of accepted problems in the tasklist.
! It cannot remove problem currently, but hide them.
-- Added random unaccepted problem in tasklist.
: Of course, either of the functions can be configurated in the dashboard.
=> VER 2.6.0 TaskList Ex

extend-luogu.user.js
*M Colors List
-- Colors List
: Developers can only use the colors in Colors List.
*M judge_problem
$ judge_problem
: Using more elegant way.
*M exlg-dash
-- added cursor style
=> VER 2.7.8 Colors List, Judge Problem, Exlg Dash

extend-luogu.user.js
*M styl
*- styl
: Add more colors.
=> VER 2.7.9 Add Colors

extend-luogu.user.js
-M benben-emoticon
: Users can input emoticon in benben.
*M emoticon
*- styl
: Use same style with benben-emoticon.
*< eslint
=> VER 2.8.1 Benben Emoticon

extend-luogu.user.js
*M emoticon
: Fix shortcut input.
=> VER 2.8.9 Emoticon

extend-luogu.user.js
=> VER 2.8.13 Emoticon

extend-luogu.user.js
-M hide-solution
-- Hide solution button in problem pages.
-- Jump to original problem pages from solution pages automatically.
! This function enables after loading main content.
=> Ver 2.9.0&2.9.1 Hide Solution

extend-luogu.user.js
*M emoticon
: Add emos.
*M benben-emoticon
: Add emos.
=> VER 2.9.2 Emoticon, Benben Emoticon

extend-luogu.user.js
*M emoticon
: Add emos.
*M benben-emoticon
: Add emos.
=> VER 2.9.3 Emoticon, Benben Emoticon

extend-luogu.user.js
*M emoticon
: Add emos.
*M benben-emoticon
: Add emos.
=> VER 2.9.4 Emoticon, Benben Emoticon

extend-luogu.user.js
*M benben
: 可以使用查看更多键了
! 无法显示加载中
& 访问速度较慢
=> VER 2.10.4 BenBen

extend-luogu.user.js
=> fix benben

extend-luogu.user.js
-M original-difficulty
: Show original difficulty in remoteJudge pages
=> Original difficulty display

.eslintrc.js, .gitignore, extend-luogu.user.js
-M virtual-participation
: 创建重现赛，仿真测试
: 无法创建用来 vp 的比赛和未结束比赛的重现赛
! 自己能看到自己创建比赛里的题目
*- 如果洛谷前端加载失败，exlg 将会中止加载
*M user-problem-color
: 加快了比较
*< 用 lg_dat 和 lg_usr 代替了 _feInjection
-# .gitignore
: 加入了 .vscode/
*# .eslintrc.js
: 加入了 argsIgnorePattern
=> Virtual Participation

extend-luogu.user.js
^M virtual-participation
: 删除了 __CLASS_NAME 字段，确认无用且会造成 JSON 传递问题。
=> Fix JSON parse

extend-luogu.user.js
\*M user-problem-color
: 加快了比较
! 卸载比加载还慢
^M original-difficulty
: 修复了部分题面中有\*的题目无法正确显示难度的问题
! 用 jQuery 导致速度降低
=> Optimize Problem Compare

src/main.js, src/modules/blog.js
=> add blog format

doc/module/blog.md, doc/module/module.md, src/modules/blog.js
-- 为 markdown 编辑器添加快捷键（Ctrl+B 粗体，Ctrl+I 斜体，Ctrl+Shift+X 删除线）
-? 为 blog 模块添加文档
=> add hotkeys for markdown editor

src/modules/sponsor.js
=> Add support for new backend

.github/workflows/node.js.yml, scripts/tag.py
```
*@ Only build when commit starts with VER
-@ Release automatically
```
=> [CI] GitHub Actions: Auto release

src/modules/benben.js
-M benben-delete
（为啥我本地能过 eslint，是我没配置好吗 /qd）
=> Add Benben Delete
